# Generated by Django 2.1.5 on 2019-02-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decreto_143_18', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_inversiones',
            name='tipo',
            field=models.CharField(choices=[('Maquinaria', 'Maquinaria'), ('Equipos', 'Equipos'), ('Instalaciones', 'Instalaciones'), ('Materiales', 'Materiales'), ('Mano de Obra', 'Mano de Obra'), ('Leyes Sociales', 'Leyes Sociales'), ('Honorarios', 'Honorarios')], default='Maquinaria', max_length=100, unique=True),
        ),
    ]
